V2 (#1)
* Update build-and-push-docker.yaml

* Update build-and-push-docker.yaml

* Update build-and-push-docker.yaml

* Update deploy-k8s.yaml

* Update deploy-k8s.yaml

diff --git a/.github/workflows/build-and-push-docker.yaml b/.github/workflows/build-and-push-docker.yaml
--- a/.github/workflows/build-and-push-docker.yaml
+++ b/.github/workflows/build-and-push-docker.yaml
@@ -9,7 +9,10 @@ on:
         required: true
         type: string
       PACKAGE_NAME:
-        required: true
+        required: false
+        type: string
+      ACR_RUN_FILE:
+        required: false
         type: string
       AZ_REGISTRY_URL:
         required: true
@@ -24,6 +27,11 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+    - name: Wrong configuration
+      if: "${{ (inputs.PACKAGE_NAME != '') && (inputs.ACR_RUN_FILE != '') }}"
+      run: |
+        echo "PACKAGE_NAME and ACR_RUN_FILE cannot be declared in the same run"
+        exit 1
     - name: Checkout with dependencies
       uses: actions/checkout@v3
       env:
@@ -44,6 +52,13 @@ jobs:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
     # Container build and push to a Azure Container Registry (ACR)        
-    - name: Build and push image
+    - name: Build single image
+      if: "${{ inputs.PACKAGE_NAME != '' }}"
       run: |
         az acr build -t ${{ inputs.AZ_REGISTRY_URL }}/${{ inputs.PACKAGE_NAME }}:${{ inputs.APP_VERSION }} -r $(echo ${{ inputs.AZ_REGISTRY_URL }} | cut -d. -f1) -f ${{ inputs.DOCKERFILE_NAME }} .
+    
+    - name: Build from acr run file
+      if: "${{ inputs.ACR_RUN_FILE != '' }}"
+      run: |
+        az acr run -f ${{ inputs.ACR_RUN_FILE }} -r $(echo ${{ inputs.AZ_REGISTRY_URL }} | cut -d. -f1) --set TAG_NAME=${{ inputs.APP_VERSION }} .
+        
